version: '3'
services:
  auctionserver1:
    build:  
      context: ./disysminiproject3
      dockerfile: Dockerfile
      args:
        APPTYPE: server
    env_file:
      - server.env
      - .env
    environment:
      - ID=1
    ports:
      - 8080:8080
  auctionserver2:
    build:  
      context: ./disysminiproject3
      dockerfile: Dockerfile
      args:
        APPTYPE: server
    env_file:
      - server.env
      - .env
    environment:
      - ID=2
    ports:
      - 8080:8081
  auctionserver3:
    build:  
      context: ./disysminiproject3
      dockerfile: Dockerfile
      args:
        APPTYPE: server
    env_file:
      - server.env
      - .env
    environment:
      - ID=3
    ports:
      - 8080:8082
  frontend:
    build:
      context: ./disysminiproject3
      dockerfile: Dockerfile
      args:
        APPTYPE: frontend
    env_file:
      - frontend.env
      - .env
    ports:
      - 8080:8000
